### ISSUE TITLE
atlas style in pyroot already available as part of rootpy

### ISSUE THREAD

**Issue by kratsg** [joeycarter/atlas-plot-utils#1]
I just noticed this -- but was checking to see if you were aware of an existing project http://www.rootpy.org/auto_examples/plotting/plot_matplotlib_hist.html which has ATLAS style baked in.

**Comment by joeycarter** [comment]
Hi @kratsg,

Thanks for pointing that out. It looks like rootpy is using a slightly modified version of the official ATLAS style guidelines from the ATLAS publication committee: https://github.com/rootpy/rootpy/blob/master/rootpy/plotting/style/atlas/style.py.

So in fact we're both implementing a python version of the official ATLAS style :). The focus of atlas-plots is more to simplify the process of reading TTrees from root files and producing histograms, and I want to try to limit the number python packages it depends on, so I'll leave it as it is for now.
